// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIFO5-VAkRt5qWBaD85Z1xn_sFZXULlKI',
    appId: '1:1049964003482:web:ae012547c85c43755f9f23',
    messagingSenderId: '1049964003482',
    projectId: 'pine-cadf8',
    authDomain: 'pine-cadf8.firebaseapp.com',
    storageBucket: 'pine-cadf8.firebasestorage.app',
    measurementId: 'G-B5G2BCEZS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf75DbQuoSj0q8B5ZUdmBftWTi8rgTZeQ',
    appId: '1:1049964003482:android:daac37f0bdaaaf585f9f23',
    messagingSenderId: '1049964003482',
    projectId: 'pine-cadf8',
    storageBucket: 'pine-cadf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjCrNVzTx7VvfAikU19XzLu5s1L4Ry9WI',
    appId: '1:1049964003482:ios:45a8028a465368b15f9f23',
    messagingSenderId: '1049964003482',
    projectId: 'pine-cadf8',
    storageBucket: 'pine-cadf8.firebasestorage.app',
    androidClientId: '1049964003482-2f2pgnvr772cl4enhpfg1ml024iif666.apps.googleusercontent.com',
    iosClientId: '1049964003482-8g5suoj5mvurv30h6biadaotf7bk028l.apps.googleusercontent.com',
    iosBundleId: 'com.example.pineAdminPanel',
  );
}
